namespace: wilkenweb-prod
resources:
- ../../base
patches:
- path: patch-image.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: registry.digitalocean.com/wilkenweb/app
  newName: registry.digitalocean.com/wilkenweb/app
  newTag: c18114d
