apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-redirect
  namespace: wilkenweb-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://xeroeffort.com$request_uri
spec:
  rules:
    - host: seanwilken.com
      http:
        paths:
          - path: /shop
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80

    - host: www.seanwilken.com
      http:
        paths:
          - path: /shop
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80

    - host: xeroeffort.com
      http:
        paths:
          - path: /shop
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80

    - host: www.xeroeffort.com
      http:
        paths:
          - path: /shop
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80